version: "3.8"

services:
  nrt_deploy:
    build:
      context: .
    container_name: nrt_deploy
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    environment:
      - CURRENT_UID=${CURRENT_UID}
      - TZ="Africa/Nairobi"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock